# Strings

In [6]:
print("hello".upper())
print("hello".lower())
print("hello".title())
print("hello".count('l'))
print("hello".replace('o','u'))

HELLO
hello
Hello
2
hellu

# Variables

In [7]:
message_1 = "I'm learning python"

In [8]:
 message_1

"I'm learning python"

In [9]:
message_2 = "i am feeling good"
message_1 + message_2

"I'm learning pythoni am feeling good"

In [12]:
message_1 +' '+ message_2

"I'm learning python i am feeling good"

In [15]:
#variable string
f'{message_1} oh ic {message_2}'

"I'm learning python oh ic i am feeling good"

# Lists

In [3]:
countries= ['us','pakistan','gaza',0.3,4,'us']
countries

['us', 'pakistan', 'gaza', 0.3, 4, 'us']

In [7]:
print(countries[0])
print(countries[-1])
print(countries[-2])

us
us
4

In [8]:
 #slicing  listname[startindex:stop index]
countries[2:4]

['gaza', 0.3]

In [9]:
countries[1:]

['pakistan', 'gaza', 0.3, 4, 'us']

In [10]:
countries[:2]

['us', 'pakistan']

# adding Elements to list

In [11]:
#appending
countries.append('canada')
countries[-1]

'canada'

In [12]:
countries

['us', 'pakistan', 'gaza', 0.3, 4, 'us', 'canada']

In [13]:
countries.insert(0, 'shaheen')
countries[0]

'shaheen'

In [14]:
countries

['shaheen', 'us', 'pakistan', 'gaza', 0.3, 4, 'us', 'canada']

In [16]:
 countries2=['kashif','kamran']

In [17]:
countries + countries2

['shaheen',
 'us',
 'pakistan',
 'gaza',
 0.3,
 4,
 'us',
 'canada',
 'kashif',
 'kamran']

In [18]:
nested_list= [countries,countries2]

In [19]:
nested_list

[['shaheen', 'us', 'pakistan', 'gaza', 0.3, 4, 'us', 'canada'],
 ['kashif', 'kamran']]

# Removing an element

In [20]:
countries.remove('us')
countries

['shaheen', 'pakistan', 'gaza', 0.3, 4, 'us', 'canada']

In [21]:
countries.remove('us')
countries

['shaheen', 'pakistan', 'gaza', 0.3, 4, 'canada']

In [22]:
countries.pop(-1)

'canada'

In [23]:
countries

['shaheen', 'pakistan', 'gaza', 0.3, 4]

In [25]:
nested_list

[['shaheen', 'pakistan', 'gaza', 0.3, 4], ['kashif', 'kamran']]

In [26]:
del countries[-1]

In [27]:
countries

['shaheen', 'pakistan', 'gaza', 0.3]

# Sorting list

In [34]:
numbers=[2,6,8,2,4,1]
numbers.sort()
numbers

[1, 2, 2, 4, 6, 8]

In [33]:
numbers.sort(reverse=True)
numbers

[8, 6, 4, 2, 2, 1]

# Update an element

In [36]:
numbers[0] = 10000
numbers

[10000, 2, 2, 4, 6, 8]

# Copying a List

In [37]:
countries[:]

['shaheen', 'pakistan', 'gaza', 0.3]

In [38]:
new_list = countries

In [39]:
new_list

['shaheen', 'pakistan', 'gaza', 0.3]

In [40]:
new_list2 = countries.copy()

In [41]:
new_list2

['shaheen', 'pakistan', 'gaza', 0.3]

# Distionaries

In [42]:
my_dist = {'key1':'value1','key2':'value2'}
my_dist

{'key1': 'value1', 'key2': 'value2'}

In [7]:
saim = {'Name':"Muhammad saim",'age': 20, 'blood group':'B-positive'}
saim

{'Name': 'Muhammad saim', 'age': 20, 'blood group': 'B-positive'}

In [8]:
saim.keys()

dict_keys(['Name', 'age', 'blood group'])

In [9]:
saim.values()

dict_values(['Muhammad saim', 20, 'B-positive'])

In [10]:
saim.items()

dict_items([('Name', 'Muhammad saim'), ('age', 20), ('blood group', 'B-positive')])

In [19]:
saim['height']= '7 feet'

In [20]:
saim

{'Name': 'Muhammad saim',
 'age': 20,
 'blood group': 'B-positive',
 'height': '7 feet'}

In [28]:
saim.update({'height':'30 feet'})

In [29]:
saim

{'Name': 'Muhammad saim',
 'age': 20,
 'blood group': 'B-positive',
 'height': '30 feet'}

# copy of dict

In [17]:
new_dictionary = saim.copy()
new_dictionary

{'Name': 'Muhammad saim',
 'age': 20,
 'blood group': 'B-positive',
 'height': '6.1 feet'}

In [25]:
 new_dictionary

{'Name': 'Muhammad saim',
 'age': 20,
 'blood group': 'B-positive',
 'height': '6.1 feet'}

In [26]:
new_dict = saim

In [30]:
new_dict

{'Name': 'Muhammad saim',
 'age': 20,
 'blood group': 'B-positive',
 'height': '30 feet'}

# Removing From Dictionay

In [31]:
new_dict.pop('Name')

'Muhammad saim'

In [32]:
new_dict

{'age': 20, 'blood group': 'B-positive', 'height': '30 feet'}

In [33]:
del  new_dict['age']

In [34]:
new_dict

{'blood group': 'B-positive', 'height': '30 feet'}

In [35]:
new_dict.clear()

In [37]:
new_dict

{}

# For loop

In [41]:
countries= ['us','pakistan','gaza',0.3,4,'us']
for country in countries:
    print(country)

us
pakistan
gaza
0.3
4
us

In [44]:
for i,country in enumerate(countries):
    print(i)
    print(country)

0
us
1
pakistan
2
gaza
3
0.3
4
4
5
us

In [45]:
new_dictionary

{'Name': 'Muhammad saim',
 'age': 20,
 'blood group': 'B-positive',
 'height': '6.1 feet'}

In [48]:
for key, value in new_dictionary.items():
    print(key)
    print(value)

Name
Muhammad saim
age
20
blood group
B-positive
height
6.1 feet

# Built-in Functions

In [49]:
countries= ['us','pakistan','gaza',0.3,4,'us']
len(countries)

6

In [50]:
max([23,43,65,77,32,889,6])

889

In [51]:
min([23,43,65,77,32,889,6])

6

In [52]:
type(countries)

list

In [54]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9

# OS Module

In [55]:
import os

In [57]:
os.getcwd()

'C:\\Users\\Muham\\Desktop\\ai engineering\\python fo datascience'

In [58]:
os.listdir()

['.ipynb_checkpoints', 'Python for Datascience.ipynb']

In [59]:
os.makedirs("love u python")

# Creating a dataframe from an array

In [4]:
import pandas as pd
import numpy as np

## Option 1

In [63]:
#creating an array 
data = np.array([[1,4] , [3,4] , [4,5]])

In [66]:
# creating a dataframe
df=pd.DataFrame(data,index=['row1','row2','row3'],columns=['column1','column2'])

In [67]:
df

      column1  column2
row1        1        4
row2        3        4
row3        4        5

## Option2

In [68]:
#creating an array with list shape
data = [[1,4] , [3,4] , [4,5]]

In [69]:
df=pd.DataFrame(data,index=['row1','row2','row3'],columns=['column1','column2'])

In [70]:
df

      column1  column2
row1        1        4
row2        3        4
row3        4        5

# Creating Dataframe From a Disctionary

In [72]:
#list used for this example
states = ['california', 'Texas','Florida','New York']
population =[23233223,3434334,3433433,34334334]

In [73]:
# sorting lists with a dictionary
dict_states ={'States':states,'Pouplation':population}

In [74]:
#creating dataframe
df_population=pd.DataFrame(dict_states)

In [75]:
df_population

       States  Pouplation
0  california    23233223
1       Texas     3434334
2     Florida     3433433
3    New York    34334334

# Creating Dataframe From a CSV File

In [5]:
#reading from csv file
df_exams=pd.read_csv('StudentsPerformance.csv')

In [79]:
#show First Five rows in a Datframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [80]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [81]:
# head method
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [82]:
# tails method
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [83]:
#show desired n rows
df_exams.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [84]:
#show desired n rows
df_exams.tail(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [85]:
df_exams.shape  #(r,c)

(1000, 8)

In [87]:
#display desired
pd.set_option('display.max_rows',1000)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
61,male,group A,some high school,free/reduced,none,39,39,34
62,male,group A,associate's degree,free/reduced,none,62,61,55
63,female,group C,associate's degree,standard,none,69,80,71
64,female,group D,some high school,standard,none,59,58,59
65,male,group B,some high school,standard,none,67,64,61
66,male,group D,some high school,free/reduced,none,45,37,37
67,female,group C,some college,standard,none,60,72,74
68,male,group B,associate's degree,free/reduced,none,61,58,56
69,female,group C,associate's degree,standard,none,39,64,57
70,female,group D,some college,free/reduced,completed,58,63,73
71,male,group D,some college,standard,completed,63,55,63
72,female,group A,associate's degree,free/reduced,none,41,51,48
73,male,group C,some high school,free/reduced,none,61,57,56
74,male,group C,some high school,standard,none,49,49,41
75,male,group B,associate's degree,free/reduced,none,44,41,38
76,male,group E,some high school,standard,none,30,26,22
77,male,group A,bachelor's degree,standard,completed,80,78,81
78,female,group D,some high school,standard,completed,61,74,72
79,female,group E,master's degree,standard,none,62,68,68
80,female,group B,associate's degree,standard,none,47,49,50
81,male,group B,high school,free/reduced,none,49,45,45
82,male,group A,some college,free/reduced,completed,50,47,54
83,male,group E,associate's degree,standard,none,72,64,63
84,male,group D,high school,free/reduced,none,42,39,34
85,female,group C,some college,standard,none,73,80,82
86,female,group C,some college,free/reduced,none,76,83,88
87,female,group D,associate's degree,standard,none,71,71,74
88,female,group A,some college,standard,none,58,70,67
89,female,group D,some high school,standard,none,73,86,82
90,female,group C,bachelor's degree,standard,none,65,72,74
91,male,group C,high school,free/reduced,none,27,34,36
92,male,group C,high school,standard,none,71,79,71
93,male,group C,associate's degree,free/reduced,completed,43,45,50
94,female,group B,some college,standard,none,79,86,92
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62
100,male,group B,some college,standard,none,79,67,67
101,male,group D,bachelor's degree,standard,completed,68,74,74
102,female,group D,associate's degree,standard,none,85,91,89
103,male,group B,high school,standard,completed,60,44,47
104,male,group C,some college,standard,completed,98,86,90
105,female,group C,some college,standard,none,58,67,72
106,female,group D,master's degree,standard,none,87,100,100
107,male,group E,associate's degree,standard,completed,66,63,64
108,female,group B,associate's degree,free/reduced,none,52,76,70
109,female,group B,some high school,standard,none,70,64,72
110,female,group D,associate's degree,free/reduced,completed,77,89,98
111,male,group C,high school,standard,none,62,55,49
112,male,group A,associate's degree,standard,none,54,53,47
113,female,group D,some college,standard,none,51,58,54
114,female,group E,bachelor's degree,standard,completed,99,100,100
115,male,group C,high school,standard,none,84,77,74
116,female,group B,bachelor's degree,free/reduced,none,75,85,82
117,female,group D,bachelor's degree,standard,none,78,82,79
118,female,group D,some high school,standard,none,51,63,61
119,female,group C,some college,standard,none,55,69,65
120,female,group C,bachelor's degree,standard,completed,79,92,89
121,male,group B,associate's degree,standard,completed,91,89,92
122,female,group C,some college,standard,completed,88,93,93
123,male,group D,high school,free/reduced,none,63,57,56
124,male,group E,some college,standard,none,83,80,73
125,female,group B,high school,standard,none,87,95,86
126,male,group B,some high school,standard,none,72,68,67
127,male,group D,some college,standard,completed,65,77,74
128,male,group D,master's degree,standard,none,82,82,74
129,female,group A,bachelor's degree,standard,none,51,49,51
130,male,group D,master's degree,standard,none,89,84,82
131,male,group C,some high school,free/reduced,completed,53,37,40
132,male,group E,some college,free/reduced,completed,87,74,70
133,female,group C,some college,standard,completed,75,81,84
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75
135,male,group C,bachelor's degree,standard,none,58,55,48
136,male,group B,some high school,standard,completed,51,54,41
137,male,group E,high school,standard,none,70,55,56
138,female,group C,associate's degree,standard,none,59,66,67
139,male,group D,some college,standard,completed,71,61,69
140,female,group D,some high school,standard,none,76,72,71
141,female,group C,some college,free/reduced,none,59,62,64
142,female,group E,some college,free/reduced,completed,42,55,54
143,male,group A,high school,standard,none,57,43,47
144,male,group D,some college,standard,none,88,73,78
145,female,group C,some college,free/reduced,none,22,39,33
146,male,group B,some high school,standard,none,88,84,75
147,male,group C,associate's degree,free/reduced,none,73,68,66
148,female,group D,bachelor's degree,standard,completed,68,75,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
150,male,group A,some high school,standard,completed,62,67,69
151,male,group A,bachelor's degree,standard,none,77,67,68
152,female,group B,associate's degree,standard,completed,59,70,66
153,male,group D,bachelor's degree,standard,none,54,49,47
154,male,group D,some high school,standard,none,62,67,61
155,female,group C,some college,standard,completed,70,89,88
156,female,group E,high school,free/reduced,completed,66,74,78
157,male,group B,some college,free/reduced,none,60,60,60
158,female,group B,associate's degree,standard,completed,61,86,87
159,male,group D,associate's degree,free/reduced,none,66,62,64
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78
168,female,group B,high school,standard,completed,68,83,78
169,female,group C,some college,free/reduced,completed,67,75,70
170,male,group A,high school,standard,completed,72,73,74
171,male,group E,some high school,standard,none,94,88,78
172,female,group D,some college,standard,none,79,86,81
173,female,group C,associate's degree,standard,none,63,67,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54
175,female,group C,master's degree,standard,completed,81,91,87
176,female,group B,high school,free/reduced,completed,46,54,58
177,female,group C,associate's degree,standard,completed,71,77,77
178,female,group B,master's degree,free/reduced,completed,52,70,62
179,female,group D,some high school,standard,completed,97,100,100
180,male,group C,master's degree,free/reduced,completed,62,68,75
181,female,group C,some college,free/reduced,none,46,64,66
182,female,group E,high school,standard,none,50,50,47
183,female,group D,associate's degree,standard,none,65,69,70
184,male,group C,some high school,free/reduced,completed,45,52,49
185,male,group C,associate's degree,free/reduced,completed,65,67,65
186,male,group E,high school,standard,none,80,76,65
187,male,group D,some high school,standard,completed,62,66,68
188,male,group B,some high school,free/reduced,none,48,52,45
189,female,group C,bachelor's degree,standard,none,77,88,87
190,female,group E,associate's degree,standard,none,66,65,69
191,male,group D,some college,standard,completed,76,83,79
192,female,group B,some high school,standard,none,62,64,66
193,male,group D,some college,standard,completed,77,62,62
194,female,group C,master's degree,standard,completed,69,84,85
195,male,group D,associate's degree,standard,none,61,55,52
196,male,group C,some high school,free/reduced,completed,59,69,65
197,male,group E,high school,free/reduced,none,55,56,51
198,female,group B,some college,free/reduced,none,45,53,55
199,female,group B,bachelor's degree,free/reduced,none,78,79,76
200,female,group C,associate's degree,standard,completed,67,84,86
201,female,group D,some college,free/reduced,none,65,81,77
202,male,group C,associate's degree,standard,none,69,77,69
203,female,group B,associate's degree,standard,none,57,69,68
204,male,group C,some college,standard,none,59,41,42
205,male,group D,some high school,standard,completed,74,71,78
206,male,group E,bachelor's degree,standard,none,82,62,62
207,male,group E,high school,standard,completed,81,80,76
208,female,group B,some college,free/reduced,none,74,81,76
209,female,group B,some college,free/reduced,none,58,61,66
210,male,group D,some high school,free/reduced,completed,80,79,79
211,male,group C,some college,free/reduced,none,35,28,27
212,female,group C,high school,free/reduced,none,42,62,60
213,male,group C,associate's degree,free/reduced,completed,60,51,56
214,male,group E,high school,standard,completed,87,91,81
215,male,group B,some high school,standard,completed,84,83,75
216,female,group E,associate's degree,free/reduced,completed,83,86,88
217,female,group C,high school,free/reduced,none,34,42,39
218,male,group B,high school,free/reduced,none,66,77,70
219,male,group B,some high school,standard,completed,61,56,56
220,female,group D,high school,standard,completed,56,68,74
221,male,group B,associate's degree,standard,none,87,85,73
222,female,group C,some high school,free/reduced,none,55,65,62
223,male,group D,some high school,standard,none,86,80,75
224,female,group B,associate's degree,standard,completed,52,66,73
225,female,group E,master's degree,free/reduced,none,45,56,54
226,female,group C,some college,standard,none,72,72,71
227,male,group D,high school,standard,none,57,50,54
228,male,group A,some high school,free/reduced,none,68,72,64
229,female,group C,some college,standard,completed,88,95,94
230,male,group D,some college,standard,none,76,64,66
231,male,group C,associate's degree,standard,none,46,43,42
232,female,group B,bachelor's degree,standard,none,67,86,83
233,male,group E,some high school,standard,none,92,87,78
234,male,group C,bachelor's degree,standard,completed,83,82,84
235,male,group D,associate's degree,standard,none,80,75,77
236,male,group D,bachelor's degree,free/reduced,none,63,66,67
237,female,group D,some high school,standard,completed,64,60,74
238,male,group B,some college,standard,none,54,52,51
239,male,group C,associate's degree,standard,none,84,80,80
240,male,group D,high school,free/reduced,completed,73,68,66
241,female,group E,bachelor's degree,standard,none,80,83,83
242,female,group D,high school,standard,none,56,52,55
243,male,group E,some college,standard,none,59,51,43
244,male,group D,some high school,standard,none,75,74,69
245,male,group C,associate's degree,standard,none,85,76,71
246,male,group E,associate's degree,standard,none,89,76,74
247,female,group B,high school,standard,completed,58,70,68
248,female,group B,high school,standard,none,65,64,62
249,male,group C,high school,standard,none,68,60,53
250,male,group A,some high school,standard,completed,47,49,49
251,female,group D,some college,free/reduced,none,71,83,83
252,female,group B,some high school,standard,completed,60,70,70
253,male,group D,master's degree,standard,none,80,80,72
254,male,group D,high school,standard,none,54,52,52
255,female,group E,some college,standard,none,62,73,70
256,female,group C,associate's degree,free/reduced,none,64,73,68
257,male,group C,associate's degree,standard,completed,78,77,77
258,female,group B,some college,standard,none,70,75,78
259,female,group C,master's degree,free/reduced,completed,65,81,81
260,female,group C,some high school,free/reduced,completed,64,79,77
261,male,group C,some college,standard,completed,79,79,78
262,female,group C,some high school,free/reduced,none,44,50,51
263,female,group E,high school,standard,none,99,93,90
264,male,group D,high school,standard,none,76,73,68
265,male,group D,some high school,free/reduced,none,59,42,41
266,female,group C,bachelor's degree,standard,none,63,75,81
267,female,group D,high school,standard,none,69,72,77
268,female,group D,associate's degree,standard,completed,88,92,95
269,female,group E,some college,free/reduced,none,71,76,70
270,male,group C,bachelor's degree,standard,none,69,63,61
271,male,group C,some college,standard,none,58,49,42
272,female,group D,associate's degree,free/reduced,none,47,53,58
273,female,group D,some college,standard,none,65,70,71
274,male,group B,some college,standard,completed,88,85,76
275,male,group C,bachelor's degree,standard,none,83,78,73
276,female,group C,some high school,standard,completed,85,92,93
277,female,group E,high school,standard,completed,59,63,75
278,female,group C,some high school,free/reduced,none,65,86,80
279,male,group B,bachelor's degree,free/reduced,none,73,56,57
280,male,group D,high school,standard,none,53,52,42
281,male,group D,high school,standard,none,45,48,46
282,female,group D,bachelor's degree,free/reduced,none,73,79,84
283,female,group D,some college,free/reduced,completed,70,78,78
284,female,group B,some high school,standard,none,37,46,46
285,male,group B,associate's degree,standard,completed,81,82,82
286,male,group E,associate's degree,standard,completed,97,82,88
287,female,group B,some high school,standard,none,67,89,82
288,male,group B,bachelor's degree,free/reduced,none,88,75,76
289,male,group E,some high school,standard,completed,77,76,77
290,male,group C,associate's degree,standard,none,76,70,68
291,male,group D,some high school,standard,none,86,73,70
292,male,group C,some high school,standard,completed,63,60,57
293,female,group E,bachelor's degree,standard,none,65,73,75
294,male,group D,high school,free/reduced,completed,78,77,80
295,male,group B,associate's degree,free/reduced,none,67,62,60
296,male,group A,some high school,standard,completed,46,41,43
297,male,group E,associate's degree,standard,completed,71,74,68
298,male,group C,high school,free/reduced,completed,40,46,50
299,male,group D,associate's degree,free/reduced,none,90,87,75
300,male,group A,some college,free/reduced,completed,81,78,81
301,male,group D,some high school,free/reduced,none,56,54,52
302,female,group C,associate's degree,standard,completed,67,84,81
303,male,group B,associate's degree,standard,none,80,76,64
304,female,group C,associate's degree,standard,completed,74,75,83
305,male,group A,some college,standard,none,69,67,69
306,male,group E,some college,standard,completed,99,87,81
307,male,group C,some high school,standard,none,51,52,44
308,female,group B,associate's degree,free/reduced,none,53,71,67
309,female,group D,high school,free/reduced,none,49,57,52
310,female,group B,associate's degree,standard,none,73,76,80
311,male,group B,bachelor's degree,standard,none,66,60,57
312,male,group D,bachelor's degree,standard,completed,67,61,68
313,female,group C,associate's degree,free/reduced,completed,68,67,69
314,female,group C,bachelor's degree,standard,completed,59,64,75
315,male,group C,high school,standard,none,71,66,65
316,female,group D,master's degree,standard,completed,77,82,91
317,male,group C,associate's degree,standard,none,83,72,78
318,male,group B,bachelor's degree,standard,none,63,71,69
319,female,group D,associate's degree,free/reduced,none,56,65,63
320,female,group C,high school,free/reduced,completed,67,79,84
321,female,group E,high school,standard,none,75,86,79
322,female,group C,some college,standard,none,71,81,80
323,female,group C,some high school,free/reduced,none,43,53,53
324,female,group C,high school,free/reduced,none,41,46,43
325,female,group C,some college,standard,none,82,90,94
326,male,group C,some college,standard,none,61,61,62
327,male,group A,some college,free/reduced,none,28,23,19
328,male,group C,associate's degree,standard,completed,82,75,77
329,female,group B,some high school,standard,none,41,55,51
330,male,group C,high school,standard,none,71,60,61
331,male,group C,associate's degree,standard,none,47,37,35
332,male,group E,associate's degree,standard,completed,62,56,53

# Attributes of pandas

In [89]:
df_exams.shape  #(r,c)

(1000, 8)

In [91]:
df_exams.index   #shows idexes and there steps

RangeIndex(start=0, stop=1000, step=1)

In [93]:
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [95]:
#type of columns
df_exams.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

# Methods

In [96]:
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [97]:
#describing basic statistics
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# Functions

In [99]:
#obtain len of dataframe   rows only
len(df_exams)

1000

In [100]:
#highest index of the dataframe
max(df_exams)

'writing score'

In [101]:
max(df_exams.index)

999

In [102]:
type(df_exams)

pandas.core.frame.DataFrame

In [103]:
round(df_exams,2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
61,male,group A,some high school,free/reduced,none,39,39,34
62,male,group A,associate's degree,free/reduced,none,62,61,55
63,female,group C,associate's degree,standard,none,69,80,71
64,female,group D,some high school,standard,none,59,58,59
65,male,group B,some high school,standard,none,67,64,61
66,male,group D,some high school,free/reduced,none,45,37,37
67,female,group C,some college,standard,none,60,72,74
68,male,group B,associate's degree,free/reduced,none,61,58,56
69,female,group C,associate's degree,standard,none,39,64,57
70,female,group D,some college,free/reduced,completed,58,63,73
71,male,group D,some college,standard,completed,63,55,63
72,female,group A,associate's degree,free/reduced,none,41,51,48
73,male,group C,some high school,free/reduced,none,61,57,56
74,male,group C,some high school,standard,none,49,49,41
75,male,group B,associate's degree,free/reduced,none,44,41,38
76,male,group E,some high school,standard,none,30,26,22
77,male,group A,bachelor's degree,standard,completed,80,78,81
78,female,group D,some high school,standard,completed,61,74,72
79,female,group E,master's degree,standard,none,62,68,68
80,female,group B,associate's degree,standard,none,47,49,50
81,male,group B,high school,free/reduced,none,49,45,45
82,male,group A,some college,free/reduced,completed,50,47,54
83,male,group E,associate's degree,standard,none,72,64,63
84,male,group D,high school,free/reduced,none,42,39,34
85,female,group C,some college,standard,none,73,80,82
86,female,group C,some college,free/reduced,none,76,83,88
87,female,group D,associate's degree,standard,none,71,71,74
88,female,group A,some college,standard,none,58,70,67
89,female,group D,some high school,standard,none,73,86,82
90,female,group C,bachelor's degree,standard,none,65,72,74
91,male,group C,high school,free/reduced,none,27,34,36
92,male,group C,high school,standard,none,71,79,71
93,male,group C,associate's degree,free/reduced,completed,43,45,50
94,female,group B,some college,standard,none,79,86,92
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62
100,male,group B,some college,standard,none,79,67,67
101,male,group D,bachelor's degree,standard,completed,68,74,74
102,female,group D,associate's degree,standard,none,85,91,89
103,male,group B,high school,standard,completed,60,44,47
104,male,group C,some college,standard,completed,98,86,90
105,female,group C,some college,standard,none,58,67,72
106,female,group D,master's degree,standard,none,87,100,100
107,male,group E,associate's degree,standard,completed,66,63,64
108,female,group B,associate's degree,free/reduced,none,52,76,70
109,female,group B,some high school,standard,none,70,64,72
110,female,group D,associate's degree,free/reduced,completed,77,89,98
111,male,group C,high school,standard,none,62,55,49
112,male,group A,associate's degree,standard,none,54,53,47
113,female,group D,some college,standard,none,51,58,54
114,female,group E,bachelor's degree,standard,completed,99,100,100
115,male,group C,high school,standard,none,84,77,74
116,female,group B,bachelor's degree,free/reduced,none,75,85,82
117,female,group D,bachelor's degree,standard,none,78,82,79
118,female,group D,some high school,standard,none,51,63,61
119,female,group C,some college,standard,none,55,69,65
120,female,group C,bachelor's degree,standard,completed,79,92,89
121,male,group B,associate's degree,standard,completed,91,89,92
122,female,group C,some college,standard,completed,88,93,93
123,male,group D,high school,free/reduced,none,63,57,56
124,male,group E,some college,standard,none,83,80,73
125,female,group B,high school,standard,none,87,95,86
126,male,group B,some high school,standard,none,72,68,67
127,male,group D,some college,standard,completed,65,77,74
128,male,group D,master's degree,standard,none,82,82,74
129,female,group A,bachelor's degree,standard,none,51,49,51
130,male,group D,master's degree,standard,none,89,84,82
131,male,group C,some high school,free/reduced,completed,53,37,40
132,male,group E,some college,free/reduced,completed,87,74,70
133,female,group C,some college,standard,completed,75,81,84
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75
135,male,group C,bachelor's degree,standard,none,58,55,48
136,male,group B,some high school,standard,completed,51,54,41
137,male,group E,high school,standard,none,70,55,56
138,female,group C,associate's degree,standard,none,59,66,67
139,male,group D,some college,standard,completed,71,61,69
140,female,group D,some high school,standard,none,76,72,71
141,female,group C,some college,free/reduced,none,59,62,64
142,female,group E,some college,free/reduced,completed,42,55,54
143,male,group A,high school,standard,none,57,43,47
144,male,group D,some college,standard,none,88,73,78
145,female,group C,some college,free/reduced,none,22,39,33
146,male,group B,some high school,standard,none,88,84,75
147,male,group C,associate's degree,free/reduced,none,73,68,66
148,female,group D,bachelor's degree,standard,completed,68,75,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
150,male,group A,some high school,standard,completed,62,67,69
151,male,group A,bachelor's degree,standard,none,77,67,68
152,female,group B,associate's degree,standard,completed,59,70,66
153,male,group D,bachelor's degree,standard,none,54,49,47
154,male,group D,some high school,standard,none,62,67,61
155,female,group C,some college,standard,completed,70,89,88
156,female,group E,high school,free/reduced,completed,66,74,78
157,male,group B,some college,free/reduced,none,60,60,60
158,female,group B,associate's degree,standard,completed,61,86,87
159,male,group D,associate's degree,free/reduced,none,66,62,64
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78
168,female,group B,high school,standard,completed,68,83,78
169,female,group C,some college,free/reduced,completed,67,75,70
170,male,group A,high school,standard,completed,72,73,74
171,male,group E,some high school,standard,none,94,88,78
172,female,group D,some college,standard,none,79,86,81
173,female,group C,associate's degree,standard,none,63,67,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54
175,female,group C,master's degree,standard,completed,81,91,87
176,female,group B,high school,free/reduced,completed,46,54,58
177,female,group C,associate's degree,standard,completed,71,77,77
178,female,group B,master's degree,free/reduced,completed,52,70,62
179,female,group D,some high school,standard,completed,97,100,100
180,male,group C,master's degree,free/reduced,completed,62,68,75
181,female,group C,some college,free/reduced,none,46,64,66
182,female,group E,high school,standard,none,50,50,47
183,female,group D,associate's degree,standard,none,65,69,70
184,male,group C,some high school,free/reduced,completed,45,52,49
185,male,group C,associate's degree,free/reduced,completed,65,67,65
186,male,group E,high school,standard,none,80,76,65
187,male,group D,some high school,standard,completed,62,66,68
188,male,group B,some high school,free/reduced,none,48,52,45
189,female,group C,bachelor's degree,standard,none,77,88,87
190,female,group E,associate's degree,standard,none,66,65,69
191,male,group D,some college,standard,completed,76,83,79
192,female,group B,some high school,standard,none,62,64,66
193,male,group D,some college,standard,completed,77,62,62
194,female,group C,master's degree,standard,completed,69,84,85
195,male,group D,associate's degree,standard,none,61,55,52
196,male,group C,some high school,free/reduced,completed,59,69,65
197,male,group E,high school,free/reduced,none,55,56,51
198,female,group B,some college,free/reduced,none,45,53,55
199,female,group B,bachelor's degree,free/reduced,none,78,79,76
200,female,group C,associate's degree,standard,completed,67,84,86
201,female,group D,some college,free/reduced,none,65,81,77
202,male,group C,associate's degree,standard,none,69,77,69
203,female,group B,associate's degree,standard,none,57,69,68
204,male,group C,some college,standard,none,59,41,42
205,male,group D,some high school,standard,completed,74,71,78
206,male,group E,bachelor's degree,standard,none,82,62,62
207,male,group E,high school,standard,completed,81,80,76
208,female,group B,some college,free/reduced,none,74,81,76
209,female,group B,some college,free/reduced,none,58,61,66
210,male,group D,some high school,free/reduced,completed,80,79,79
211,male,group C,some college,free/reduced,none,35,28,27
212,female,group C,high school,free/reduced,none,42,62,60
213,male,group C,associate's degree,free/reduced,completed,60,51,56
214,male,group E,high school,standard,completed,87,91,81
215,male,group B,some high school,standard,completed,84,83,75
216,female,group E,associate's degree,free/reduced,completed,83,86,88
217,female,group C,high school,free/reduced,none,34,42,39
218,male,group B,high school,free/reduced,none,66,77,70
219,male,group B,some high school,standard,completed,61,56,56
220,female,group D,high school,standard,completed,56,68,74
221,male,group B,associate's degree,standard,none,87,85,73
222,female,group C,some high school,free/reduced,none,55,65,62
223,male,group D,some high school,standard,none,86,80,75
224,female,group B,associate's degree,standard,completed,52,66,73
225,female,group E,master's degree,free/reduced,none,45,56,54
226,female,group C,some college,standard,none,72,72,71
227,male,group D,high school,standard,none,57,50,54
228,male,group A,some high school,free/reduced,none,68,72,64
229,female,group C,some college,standard,completed,88,95,94
230,male,group D,some college,standard,none,76,64,66
231,male,group C,associate's degree,standard,none,46,43,42
232,female,group B,bachelor's degree,standard,none,67,86,83
233,male,group E,some high school,standard,none,92,87,78
234,male,group C,bachelor's degree,standard,completed,83,82,84
235,male,group D,associate's degree,standard,none,80,75,77
236,male,group D,bachelor's degree,free/reduced,none,63,66,67
237,female,group D,some high school,standard,completed,64,60,74
238,male,group B,some college,standard,none,54,52,51
239,male,group C,associate's degree,standard,none,84,80,80
240,male,group D,high school,free/reduced,completed,73,68,66
241,female,group E,bachelor's degree,standard,none,80,83,83
242,female,group D,high school,standard,none,56,52,55
243,male,group E,some college,standard,none,59,51,43
244,male,group D,some high school,standard,none,75,74,69
245,male,group C,associate's degree,standard,none,85,76,71
246,male,group E,associate's degree,standard,none,89,76,74
247,female,group B,high school,standard,completed,58,70,68
248,female,group B,high school,standard,none,65,64,62
249,male,group C,high school,standard,none,68,60,53
250,male,group A,some high school,standard,completed,47,49,49
251,female,group D,some college,free/reduced,none,71,83,83
252,female,group B,some high school,standard,completed,60,70,70
253,male,group D,master's degree,standard,none,80,80,72
254,male,group D,high school,standard,none,54,52,52
255,female,group E,some college,standard,none,62,73,70
256,female,group C,associate's degree,free/reduced,none,64,73,68
257,male,group C,associate's degree,standard,completed,78,77,77
258,female,group B,some college,standard,none,70,75,78
259,female,group C,master's degree,free/reduced,completed,65,81,81
260,female,group C,some high school,free/reduced,completed,64,79,77
261,male,group C,some college,standard,completed,79,79,78
262,female,group C,some high school,free/reduced,none,44,50,51
263,female,group E,high school,standard,none,99,93,90
264,male,group D,high school,standard,none,76,73,68
265,male,group D,some high school,free/reduced,none,59,42,41
266,female,group C,bachelor's degree,standard,none,63,75,81
267,female,group D,high school,standard,none,69,72,77
268,female,group D,associate's degree,standard,completed,88,92,95
269,female,group E,some college,free/reduced,none,71,76,70
270,male,group C,bachelor's degree,standard,none,69,63,61
271,male,group C,some college,standard,none,58,49,42
272,female,group D,associate's degree,free/reduced,none,47,53,58
273,female,group D,some college,standard,none,65,70,71
274,male,group B,some college,standard,completed,88,85,76
275,male,group C,bachelor's degree,standard,none,83,78,73
276,female,group C,some high school,standard,completed,85,92,93
277,female,group E,high school,standard,completed,59,63,75
278,female,group C,some high school,free/reduced,none,65,86,80
279,male,group B,bachelor's degree,free/reduced,none,73,56,57
280,male,group D,high school,standard,none,53,52,42
281,male,group D,high school,standard,none,45,48,46
282,female,group D,bachelor's degree,free/reduced,none,73,79,84
283,female,group D,some college,free/reduced,completed,70,78,78
284,female,group B,some high school,standard,none,37,46,46
285,male,group B,associate's degree,standard,completed,81,82,82
286,male,group E,associate's degree,standard,completed,97,82,88
287,female,group B,some high school,standard,none,67,89,82
288,male,group B,bachelor's degree,free/reduced,none,88,75,76
289,male,group E,some high school,standard,completed,77,76,77
290,male,group C,associate's degree,standard,none,76,70,68
291,male,group D,some high school,standard,none,86,73,70
292,male,group C,some high school,standard,completed,63,60,57
293,female,group E,bachelor's degree,standard,none,65,73,75
294,male,group D,high school,free/reduced,completed,78,77,80
295,male,group B,associate's degree,free/reduced,none,67,62,60
296,male,group A,some high school,standard,completed,46,41,43
297,male,group E,associate's degree,standard,completed,71,74,68
298,male,group C,high school,free/reduced,completed,40,46,50
299,male,group D,associate's degree,free/reduced,none,90,87,75
300,male,group A,some college,free/reduced,completed,81,78,81
301,male,group D,some high school,free/reduced,none,56,54,52
302,female,group C,associate's degree,standard,completed,67,84,81
303,male,group B,associate's degree,standard,none,80,76,64
304,female,group C,associate's degree,standard,completed,74,75,83
305,male,group A,some college,standard,none,69,67,69
306,male,group E,some college,standard,completed,99,87,81
307,male,group C,some high school,standard,none,51,52,44
308,female,group B,associate's degree,free/reduced,none,53,71,67
309,female,group D,high school,free/reduced,none,49,57,52
310,female,group B,associate's degree,standard,none,73,76,80
311,male,group B,bachelor's degree,standard,none,66,60,57
312,male,group D,bachelor's degree,standard,completed,67,61,68
313,female,group C,associate's degree,free/reduced,completed,68,67,69
314,female,group C,bachelor's degree,standard,completed,59,64,75
315,male,group C,high school,standard,none,71,66,65
316,female,group D,master's degree,standard,completed,77,82,91
317,male,group C,associate's degree,standard,none,83,72,78
318,male,group B,bachelor's degree,standard,none,63,71,69
319,female,group D,associate's degree,free/reduced,none,56,65,63
320,female,group C,high school,free/reduced,completed,67,79,84
321,female,group E,high school,standard,none,75,86,79
322,female,group C,some college,standard,none,71,81,80
323,female,group C,some high school,free/reduced,none,43,53,53
324,female,group C,high school,free/reduced,none,41,46,43
325,female,group C,some college,standard,none,82,90,94
326,male,group C,some college,standard,none,61,61,62
327,male,group A,some college,free/reduced,none,28,23,19
328,male,group C,associate's degree,standard,completed,82,75,77
329,female,group B,some high school,standard,none,41,55,51
330,male,group C,high school,standard,none,71,60,61
331,male,group C,associate's degree,standard,none,47,37,35
332,male,group E,associate's degree,standard,completed,62,56,53

# Selecting One Column

## Syntax

In [6]:
 df_exams['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [7]:
type( df_exams['gender'])

pandas.core.series.Series

In [9]:
 print(df_exams['gender'].index)
 print(df_exams['gender'].head())

RangeIndex(start=0, stop=1000, step=1)
0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

## Syntax 2

In [10]:
df_exams.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [12]:
# Selecting two columns'
df_exams[['gender','math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [13]:
type(df_exams[['gender','math score']])

pandas.core.frame.DataFrame

# Adding a new column

In [15]:
df_exams['english score'] = 70

In [16]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,english score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

# Adding using an array

In [20]:
#using numpy
language = np.arange(0,1000)

In [21]:
len(language)

1000

In [23]:
df_exams['language']= language
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,english score,language
0,female,group B,bachelor's degree,standard,none,72,72,74,70,0
1,female,group C,some college,standard,completed,69,90,88,70,1
2,female,group B,master's degree,standard,none,90,95,93,70,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,70,3
4,male,group C,some college,standard,none,76,78,75,70,4
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70,995
996,male,group C,high school,free/reduced,none,62,55,55,70,996
997,female,group C,high school,free/reduced,completed,59,71,65,70,997
998,female,group D,some college,standard,completed,68,78,77,70,998
999,female,group D,some college,free/reduced,none,77,86,86,70,999

In [24]:
# randon number

In [26]:
int_language_score = np.random.randint(1,100,size= 1000)

In [27]:
min(int_language_score)

1

In [28]:
max(int_language_score)

99

In [30]:
df_exams['int_language_score']= int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,english score,language,int_language_score
0,female,group B,bachelor's degree,standard,none,72,72,74,70,0,75
1,female,group C,some college,standard,completed,69,90,88,70,1,96
2,female,group B,master's degree,standard,none,90,95,93,70,2,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70,3,46
4,male,group C,some college,standard,none,76,78,75,70,4,5
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70,995,63
996,male,group C,high school,free/reduced,none,62,55,55,70,996,17
997,female,group C,high school,free/reduced,completed,59,71,65,70,997,3
998,female,group D,some college,standard,completed,68,78,77,70,998,97
999,female,group D,some college,free/reduced,none,77,86,86,70,999,83

In [31]:
np.random.uniform(1,100, size =1000)

array([55.95627663, 57.81648017, 86.41191745,  9.26541768, 14.87946812,
        7.08237551, 24.28026529, 18.65157089, 79.09127296, 66.46673021,
       20.13973671, 61.06882243, 36.2382638 , 76.61950473, 24.80513815,
       49.45352391,  4.30439047, 38.54556391, 24.40537963, 89.88149564,
       26.9603124 ,  7.18364088,  8.0908839 , 29.8758087 ,  4.59137569,
       25.59538266, 63.59695977, 26.15344985, 33.23166628, 96.71574252,
       84.24319139, 95.51428322, 29.21468817, 64.17764136, 13.72988458,
       59.00653506, 75.47002994, 83.71481878,  7.77830148, 70.65439904,
       61.88465659, 73.85011671, 57.25746439, 10.41623636, 23.77956223,
       91.37668854, 89.66165583, 18.85920762, 47.84937833, 43.93442732,
       83.33133266, 29.66482951, 33.6878463 , 13.58728336, 47.6251448 ,
        8.79613139, 88.17311032, 38.4330153 , 46.37722362, 76.98898104,
       59.48618048, 70.25617099, 36.79509074, 82.30482597, 57.40313579,
        5.90843351, 33.27843985, 73.78000281, 90.72113416, 22.54043439,
       81.2874938 , 26.9123513 , 54.86522329, 80.92032907, 94.7118362 ,
        7.56113325, 89.40725304, 98.20452751, 37.15991002, 88.22543816,
       44.19285686, 95.84335212, 73.5878757 ,  8.14334094, 90.61044918,
       58.94249228, 10.97846236, 36.5126181 , 38.06839932, 39.61958577,
       56.01826384, 27.29750303, 12.29324291, 47.82854849, 45.2645188 ,
       92.93742791, 24.72031338, 76.55424034, 34.90703796, 27.56230247,
       38.92110138, 80.39875022, 37.32531106, 31.29719843, 83.57262705,
       57.47840035, 97.69417568, 11.71356557, 26.44749611, 74.73800283,
       47.00354814, 59.34591172, 88.92215209,  1.62586344, 88.29066867,
       41.54779495, 86.73469917, 14.17689362, 49.42272286, 69.81121797,
       26.1638963 , 70.10195205, 39.25442097, 45.03549415, 41.10138122,
       73.95720831, 60.2525329 , 61.56023308, 15.75070491, 85.93448693,
       38.86947924, 15.53655012, 16.49976212, 18.66887532, 38.42364975,
       71.51043765, 30.39121404, 67.15161876, 99.83036602, 60.70769422,
       68.53195131, 65.60509283, 19.56663102, 94.44364519, 61.97254666,
       83.99486829, 87.34779487, 41.36407703, 83.62766089, 64.64628732,
       46.53452064, 28.66557492, 33.66682958, 11.1439683 , 46.42021341,
        6.18225229, 74.33719727, 70.62014764, 70.78496273,  8.41801188,
       72.76982133, 73.28992947, 91.20593653, 48.43396286, 11.09127426,
       13.26551674, 23.92753676, 40.64181444, 96.82291361, 42.40362505,
       74.44722553, 39.84385169, 55.23256704, 30.34183755, 16.83576865,
       12.0399726 , 64.82506667, 21.96055387, 80.58790488, 19.34572424,
       78.38961954, 91.99031527, 49.06761667, 42.11147473, 97.85930911,
       20.13941355, 52.87676274, 86.53521738, 37.85422015, 82.07898866,
       70.59189482, 75.50069241, 28.90613018,  8.84235129, 89.33227619,
       73.62734226, 59.21612195, 58.42597106, 76.22721779, 18.28678382,
       79.63705698, 57.68770253, 78.07962624, 16.97884519, 44.31968641,
       53.14502619, 27.97608756,  1.84709856, 82.65620646, 26.71258101,
       66.12616202, 69.81284395, 98.94692187,  6.72996987,  6.70138996,
       29.64228914, 88.53429987, 34.02011559, 28.44785488, 53.35742137,
       15.20696718, 61.60319785, 85.08587617, 63.58506318, 16.30932472,
       84.32331904, 38.56669427, 18.7052107 ,  8.6574185 , 61.97382767,
       56.93203697, 71.72932004, 96.15391505,  4.26322277,  2.55976687,
        8.20396313, 83.05453068, 64.39662594, 50.04526923, 91.98589913,
        3.83319624, 64.58579215, 66.42486181, 83.0500056 , 98.85327192,
       83.55922995, 34.65693493, 96.08067232, 74.19865751, 69.53784038,
       92.43642614, 31.80758264, 76.36500105, 80.02657609, 50.15112182,
       23.17014271, 64.26364452, 11.91046885, 46.24129468, 23.94559912,
       83.01639732, 17.14218817, 77.59200238,  8.06826967,  3.15997983,
       55.83436307, 55.79558726,  8.20275641, 89.10607421, 74.3789543 ,
        2.2955233 , 45.79118727, 72.39927086,  6.43042791, 60.97094646,
       17.1589987 ,  6.26648654, 57.61009086, 42.10561871, 26.74846141,
       10.51946028, 17.33408331, 39.18237989, 28.37356178, 11.11520697,
        9.10051679, 99.44616594, 73.87486709, 87.69387746, 59.84040874,
       86.50673866,  5.09231278, 75.42767043,  5.88578763, 11.3679005 ,
       32.08111456,  5.72442587, 46.82430231, 63.38050219, 91.31270394,
       49.69958386, 15.30835121, 68.25032172, 46.36912954, 44.68301563,
       37.15620942, 17.98031315, 17.39204337, 42.89984009, 29.83254025,
       30.03457978, 67.11974506, 17.92167884, 43.82783135, 23.54746394,
        2.34037612,  9.19495542, 74.04387393, 67.75722404, 17.53886792,
        2.06706915, 45.9425573 ,  9.71040489, 78.04579917, 63.32270712,
       25.25343481, 43.36019288, 45.21264206, 64.69191689, 97.60816385,
       93.99886715, 75.4942571 , 82.52525856, 69.27034109, 79.7149087 ,
       28.05236523, 71.40011301, 67.20618906, 80.41463052, 27.5614941 ,
       31.32492743, 26.33795579, 35.42554352, 15.05471417, 62.96125351,
       59.9716744 , 78.41210375, 22.91496444, 85.57011245, 95.51926247,
       25.15108797, 64.08346488, 85.63068301, 75.09748014, 61.61795488,
       42.33471246, 25.16630669,  9.18283389, 56.94434708, 61.783513  ,
       62.94396826, 91.5199377 , 23.43659   , 76.22573956, 74.70530751,
       42.16119037, 30.66336049, 17.01036825, 74.07853361, 58.21266209,
       47.75447484, 22.09779452, 55.02072152, 74.78385634, 71.56662462,
       49.38623389, 41.6396851 , 25.62816289, 73.34075698, 40.88702067,
        4.4505396 , 84.69012135, 12.82354061, 39.1845843 , 93.49645047,
       76.56686396, 87.47047717, 83.96809514, 82.50705053, 39.67544165,
       57.57297967, 17.15098011, 91.16614588,  4.67929969, 44.17993108,
       69.58291667, 60.33810282, 76.22504238, 55.8604662 , 22.78616205,
       22.45736894, 55.19191601, 16.68587228, 29.62630755, 10.22877812,
       60.24148314, 82.4669521 , 16.06402174, 92.55905465, 45.0026871 ,
       37.78357119, 78.75315286, 67.22927814, 75.21280355, 77.92913229,
       17.24546517, 96.35438079, 29.84538574, 88.29375772,  3.49778928,
       46.70866795, 59.18019099, 17.00936053, 73.52599832, 61.40767516,
       25.06693919, 41.31183193, 98.09656771, 43.22551489, 12.21653655,
       34.26249217, 90.04497759, 67.56442639, 19.529816  , 29.53086245,
       73.32196638, 32.40069284, 18.68598246, 98.23916312, 26.25526544,
       30.57222089, 61.26750138,  9.63237577,  6.50688879, 67.63828187,
       18.83506034, 90.97914858, 16.53148837,  6.60215214, 85.01379402,
       93.89587174, 86.74234661, 14.23913054, 79.81226962, 96.76076572,
       65.65887192, 74.98243975, 13.37887581, 12.14095397, 85.32911584,
       68.7888723 , 12.69476987, 76.34815108, 89.75267509, 31.71660299,
       80.50354622, 85.85060719, 15.22748028,  5.01802317, 72.36076819,
       27.63532132, 60.73221467, 37.81339934, 25.53342131, 26.18043806,
       80.10914338, 35.24729778, 60.90835273, 15.21313885, 68.48883805,
       11.13650407, 51.2950528 ,  8.14546536, 53.06080416, 61.22712914,
       51.69990461, 91.72374996, 66.29225399, 24.1097711 , 45.26124911,
       53.17864523, 25.64298084, 53.00324506, 65.2592081 , 64.00242301,
       20.88976119, 77.40998026, 57.22066466, 43.12370794, 39.23998234,
       72.65437926,  9.87824884, 68.60003493, 99.33729874, 96.77953974,
       50.19057719, 43.04380253, 21.08199516, 86.61175576, 73.24364236,
       92.04924137, 51.30473368, 75.18920293, 99.35131002, 58.28261856,
       92.8835719 , 51.25950481, 32.16356106, 27.51914581, 59.26319006,
       42.84151614, 57.8572358 , 69.24040633, 55.21208628, 82.91678882,
       39.43170549, 80.65897249, 75.37748817, 60.0399415 , 63.60448896,
        7.39645141, 53.49417753, 22.48632041, 92.84198277, 71.10574698,
       80.34073765, 20.89309118, 86.49644667, 30.51832769,  3.03330879,
       51.44950601, 17.63752532, 62.40219175, 23.73598809, 41.17811131,
       32.4056992 , 45.05369573,  4.17211179, 74.14762173, 28.04682683,
        7.8795875 , 82.42004532, 22.69716305, 33.86659176, 32.24208027,
       54.23349532, 35.44862902, 10.42826417, 71.37614009,  4.96946289,
       86.73591556, 81.45969047, 44.59622684, 28.37747231, 32.83039894,
       51.04986023, 94.68025185, 92.05668682, 29.70030045, 69.04271475,
       26.78059718, 64.3084013 , 27.5275151 , 77.08163053, 34.80895413,
       10.85502718, 86.17043688, 25.46775899, 33.80405767, 72.79267531,
        6.53411434, 89.56823758, 40.66637334, 14.60726179, 93.96126093,
       48.65640893, 58.13126512, 48.16877157, 37.78423517, 42.32001415,
       69.49127957, 89.23819259,  9.52014481,  4.80579036, 98.05822552,
       93.2995075 , 68.50546586, 48.791592  , 72.68567185, 32.86931721,
       96.47719551, 27.11725155, 99.22889053, 94.58099176, 46.16515466,
       90.4291262 , 84.98942825, 68.61055355, 96.09506994, 48.98430646,
       92.04652884, 84.71690993, 45.85162879, 13.71432463, 23.39218422,
       39.80609626, 26.08687871, 22.39034688, 48.43335749,  6.3579469 ,
       21.23114522, 50.31650027, 84.30088075, 41.63744902, 64.82769417,
       54.169194  , 83.91074124, 19.1682082 , 92.61149082, 72.87242944,
       33.31291644, 82.97736495, 11.73853492, 41.99992906,  5.41179625,
       64.37074555, 21.65925518, 69.73643223, 64.61677025, 54.5623527 ,
       53.35845448, 91.3550572 , 53.32586548, 90.81613349, 93.87361231,
       36.29881909, 83.69325039, 96.16152107, 70.19243139, 80.95044521,
       15.59044376, 14.0139486 , 31.26321316, 80.76059951, 91.30643439,
       68.28905742, 38.57565916, 98.6208474 , 33.77945923, 59.92954682,
       97.69195876,  6.17697531, 94.15860144,  7.74925211, 13.70104566,
       20.06055957, 31.92334883, 72.21739804,  8.81651029, 17.38376316,
       22.00882817, 56.90914967,  6.03458733, 36.96703488, 24.93602094,
       84.40476663, 65.23424057, 28.21867789, 64.53373281, 21.85694497,
       87.88045751, 76.9933545 , 91.90061101, 22.63349271, 52.18314692,
       50.93062132,  5.82568808, 80.5265682 , 18.30134038, 54.1467006 ,
       30.54567511, 15.07095392, 11.07336987, 85.75976248, 86.89197073,
       32.25649878, 36.36020748, 98.56482888,  3.29305451, 98.61052113,
       46.3264118 , 36.78951318, 38.74642154, 40.83719199, 99.5642943 ,
       57.35599157, 71.80253137, 27.96250999, 36.89839021, 84.91823594,
       49.79133211, 50.34535391, 85.83273082, 73.05228251, 84.15686791,
       25.51066226, 86.36301667, 38.2655287 , 92.33118729,  5.78334156,
       36.32571935, 21.32474928, 49.19317647, 12.33789351, 14.6406175 ,
       59.10154986, 39.10666702, 86.43778759, 13.32866103, 86.74463875,
       26.45279406, 82.11529848, 29.52911595, 51.7075181 ,  4.43186141,
       29.59313442, 53.39212285, 49.04981587, 66.25314556, 10.50634224,
       55.58496706, 65.58925211, 48.48408687,  3.22255257, 44.29496329,
       78.57822392, 88.86544195, 23.40391831, 34.05535573, 70.41562245,
       69.73695438, 40.99874256, 88.90450325, 46.51331835, 56.66869018,
       53.32493296, 30.75212057, 44.77382901, 28.27710662, 30.66533136,
       38.59210662, 13.32683008, 34.48073407, 52.96690353, 57.69503298,
        9.39514116, 86.58083675, 31.75640121, 81.41284573, 56.20916699,
       78.91315017, 98.39211755, 82.11722805, 92.95142455, 48.27605219,
       38.88245632, 84.23685601, 69.57019228, 27.70159211, 76.78487769,
       69.46280451, 60.45817297, 76.54727578, 84.55528407, 96.5825947 ,
       81.321163  , 39.06640928, 70.95365048, 84.1132281 , 16.2922146 ,
       73.23054908, 42.20742241, 98.03014924, 25.15314422, 16.2651634 ,
       49.95946175, 11.28275079, 84.42119032, 68.63179358, 44.55576082,
       87.26774627, 87.23643246, 16.12777482, 26.72427214, 32.47498306,
       44.01375592, 10.84821668, 89.46452028, 17.3455312 , 12.60206814,
       55.42986774, 15.55435946, 85.77765724, 68.6689253 ,  8.61009026,
       51.52498048, 78.85529458, 35.73587748, 99.92123891, 18.546245  ,
       80.60477276, 86.88394677, 95.08866863, 16.54036655,  7.67621695,
       84.90361189, 51.34989154, 22.72074156, 93.56230233, 67.10458853,
       13.29939565, 53.13225477, 82.512802  , 52.43446161, 18.69398507,
       65.43606993, 38.62674645, 23.14305706, 43.03933128, 15.81530309,
       51.32656018, 83.79808498, 63.00229218, 26.78467598, 93.11799487,
       84.31568842, 15.44279035, 37.78600821, 95.69156526, 74.15528356,
        4.819941  , 32.34741201,  2.61077058, 61.03145394, 89.68256478,
       52.96727616, 44.61823737, 97.96891981, 80.08467833, 19.33396927,
       38.94944769, 35.06696308, 21.75210623, 98.2874023 , 47.64262452,
       24.74070447, 21.3293243 , 40.3428839 , 77.46317499, 58.48543352,
       14.60623778,  4.02578123, 75.18366877, 25.91831742, 79.94188145,
       30.38124532, 40.70904916, 30.51272169, 97.49090061, 59.64430805,
       12.05682685, 10.90901024, 78.51146768, 93.13188213, 36.17226139,
       50.74304186, 94.9103315 , 37.37279636, 88.28612306, 77.05239495,
       16.66375101, 47.73347267, 93.54039918, 28.71426313, 28.08534904,
       60.35579607, 56.33808616, 44.97494811, 43.19456147, 85.98971859,
       62.31146754, 83.00556344, 66.15866866, 34.04724526, 61.52810516,
        3.01526939, 53.0842109 ,  7.82302904, 76.17725441, 68.75026181,
       25.19911477, 96.8618173 , 17.2002045 , 62.81844951, 89.63701561,
       71.88577948, 90.32940135, 33.50951807, 51.37596385, 87.84508148,
       17.90628137, 69.95772698, 17.95206033, 20.64244035, 84.95385236,
       79.41630681, 89.60991133, 34.55190866, 62.75361686, 29.22593621,
        7.38069325, 51.2725917 , 50.72873248, 43.78587705, 16.05713044,
       51.94306665,  1.0548948 ,  7.8257836 , 20.6327263 , 59.25278204,
       17.96974389, 89.20777109,  8.79783383, 87.61821311, 15.93785527,
       82.67466448, 24.51789626,  7.26671759, 98.66562541, 43.70346961,
       18.32497253, 92.67388642, 30.72381834, 62.74093147, 14.27776255,
       44.44998588, 19.33166259, 61.92010037,  2.46835284, 64.47039211,
       43.72054121, 29.42145989, 88.80499094, 42.06273456, 59.22646365,
       49.61348924, 64.17686025,  6.35518265, 47.64708248, 54.63260475,
       64.04036796, 99.06752741, 99.91284054, 83.37226936,  2.22937948,
       19.88520594, 38.60966926, 94.7234209 , 95.64116475, 26.22034395,
       61.8185718 , 18.92949194, 38.27890131, 66.10781913, 66.20643255,
       29.0580221 , 39.73190212, 33.01079259, 19.21275687, 83.39542653,
       94.08662317, 43.04238508,  4.19269671, 39.38273392, 44.56294365,
       62.07525281, 64.67681028, 61.58313467, 63.01806225,  6.52693921])

 # Assign method

In [4]:
import numpy as np
import pandas as pd
#creation of random numbers
score1 = np.random.randint(1,100,size = 1000)
score2 = np.random.randint(1,100,size = 1000)

In [5]:
series1 =pd.Series(score1, index=np.arange(0,1000))
series2 =pd.Series(score1, index=np.arange(0,1000))

In [6]:
df_exams=pd.read_csv('StudentsPerformance.csv')
df_exams = df_exams.assign(score1 = series1, score2 = series2)

In [15]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,17,17
1,female,group C,some college,standard,completed,69,90,88,36,36
2,female,group B,master's degree,standard,none,90,95,93,47,47
3,male,group A,associate's degree,free/reduced,none,47,57,44,61,61
4,male,group C,some college,standard,none,76,78,75,34,34
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,36,36
996,male,group C,high school,free/reduced,none,62,55,55,23,23
997,female,group C,high school,free/reduced,completed,59,71,65,60,60
998,female,group D,some college,standard,completed,68,78,77,4,4
999,female,group D,some college,free/reduced,none,77,86,86,41,41

 # Insert Method

In [2]:
#insert a new column at a specific position or index
df_exams=pd.read_csv('StudentsPerformance.csv')
df_exams.insert(1,'test',series1)

NameError: name 'pd' is not defined

In [19]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,17,group B,bachelor's degree,standard,none,72,72,74
1,female,36,group C,some college,standard,completed,69,90,88
2,female,47,group B,master's degree,standard,none,90,95,93
3,male,61,group A,associate's degree,free/reduced,none,47,57,44
4,male,34,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...,...
995,female,36,group E,master's degree,standard,completed,88,99,95
996,male,23,group C,high school,free/reduced,none,62,55,55
997,female,60,group C,high school,free/reduced,completed,59,71,65
998,female,4,group D,some college,standard,completed,68,78,77
999,female,41,group D,some college,free/reduced,none,77,86,86

# Average calculation

In [6]:
import numpy as np
import pandas as pd
df_exams=pd.read_csv('StudentsPerformance.csv')
df_exams['average'] = df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']/3

In [6]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,168.666667
1,female,group C,some college,standard,completed,69,90,88,188.333333
2,female,group B,master's degree,standard,none,90,95,93,216.000000
3,male,group A,associate's degree,free/reduced,none,47,57,44,118.666667
4,male,group C,some college,standard,none,76,78,75,179.000000
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,218.666667
996,male,group C,high school,free/reduced,none,62,55,55,135.333333
997,female,group C,high school,free/reduced,completed,59,71,65,151.666667
998,female,group D,some college,standard,completed,68,78,77,171.666667
999,female,group D,some college,free/reduced,none,77,86,86,191.666667

# Counting By catagory

In [12]:
df_exams['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

# Relative frequency
#### divide all the values by the sum of values

In [13]:
df_exams['gender'].value_counts(normalize= True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

# Sort a DataFrame

In [16]:
#creates only a copy
df_exams.sort_values('math score',ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
962,female,group E,associate's degree,standard,none,100,100,100,233.333333
625,male,group D,some college,standard,completed,100,97,99,230.000000
458,female,group E,bachelor's degree,standard,none,100,100,100,233.333333
623,male,group A,some college,standard,completed,100,96,86,224.666667
451,female,group E,some college,standard,none,100,92,97,224.333333
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,72.000000
787,female,group B,some college,standard,none,19,38,32,67.666667
17,female,group B,some high school,free/reduced,none,18,32,28,59.333333
980,female,group B,high school,free/reduced,none,8,24,23,39.666667
59,female,group C,some high school,free/reduced,none,0,17,10,20.333333

In [17]:
#creates only a copy
df_exams.sort_values(['math score','reading score'],ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
149,male,group E,associate's degree,free/reduced,completed,100,100,93,231.000000
458,female,group E,bachelor's degree,standard,none,100,100,100,233.333333
916,male,group E,bachelor's degree,standard,completed,100,100,100,233.333333
962,female,group E,associate's degree,standard,none,100,100,100,233.333333
625,male,group D,some college,standard,completed,100,97,99,230.000000
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,72.000000
787,female,group B,some college,standard,none,19,38,32,67.666667
17,female,group B,some high school,free/reduced,none,18,32,28,59.333333
980,female,group B,high school,free/reduced,none,8,24,23,39.666667
59,female,group C,some high school,free/reduced,none,0,17,10,20.333333

In [15]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,168.666667
1,female,group C,some college,standard,completed,69,90,88,188.333333
2,female,group B,master's degree,standard,none,90,95,93,216.000000
3,male,group A,associate's degree,free/reduced,none,47,57,44,118.666667
4,male,group C,some college,standard,none,76,78,75,179.000000
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,218.666667
996,male,group C,high school,free/reduced,none,62,55,55,135.333333
997,female,group C,high school,free/reduced,completed,59,71,65,151.666667
998,female,group D,some college,standard,completed,68,78,77,171.666667
999,female,group D,some college,free/reduced,none,77,86,86,191.666667

In [18]:
# for deep copy
df_exams.sort_values(['math score','reading score'],ascending=False, inplace= True)

In [19]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
149,male,group E,associate's degree,free/reduced,completed,100,100,93,231.000000
458,female,group E,bachelor's degree,standard,none,100,100,100,233.333333
916,male,group E,bachelor's degree,standard,completed,100,100,100,233.333333
962,female,group E,associate's degree,standard,none,100,100,100,233.333333
625,male,group D,some college,standard,completed,100,97,99,230.000000
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,72.000000
787,female,group B,some college,standard,none,19,38,32,67.666667
17,female,group B,some high school,free/reduced,none,18,32,28,59.333333
980,female,group B,high school,free/reduced,none,8,24,23,39.666667
59,female,group C,some high school,free/reduced,none,0,17,10,20.333333

In [21]:
df_exams.sort_values('race/ethnicity',ascending= True )

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
741,female,group A,associate's degree,free/reduced,none,37,57,56,112.666667
151,male,group A,bachelor's degree,standard,none,77,67,68,166.666667
811,male,group A,high school,free/reduced,none,45,47,49,108.333333
112,male,group A,associate's degree,standard,none,54,53,47,122.666667
25,male,group A,master's degree,free/reduced,none,73,74,72,171.000000
...,...,...,...,...,...,...,...,...,...
751,male,group E,some college,standard,none,68,72,65,161.666667
915,female,group E,some college,standard,none,68,70,66,160.000000
592,male,group E,bachelor's degree,standard,none,68,68,64,157.333333
479,male,group E,associate's degree,standard,none,76,71,67,169.333333
517,female,group E,some college,standard,completed,66,74,73,164.333333

In [22]:
df_exams.sort_values('race/ethnicity',ascending= True, key = lambda col:col.str.lower())

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
741,female,group A,associate's degree,free/reduced,none,37,57,56,112.666667
151,male,group A,bachelor's degree,standard,none,77,67,68,166.666667
811,male,group A,high school,free/reduced,none,45,47,49,108.333333
112,male,group A,associate's degree,standard,none,54,53,47,122.666667
25,male,group A,master's degree,free/reduced,none,73,74,72,171.000000
...,...,...,...,...,...,...,...,...,...
751,male,group E,some college,standard,none,68,72,65,161.666667
915,female,group E,some college,standard,none,68,70,66,160.000000
592,male,group E,bachelor's degree,standard,none,68,68,64,157.333333
479,male,group E,associate's degree,standard,none,76,71,67,169.333333
517,female,group E,some college,standard,completed,66,74,73,164.333333

# Shuffel method

In [1]:
import numpy as np
import random

In [3]:
new_index = np.arange(0,1000)

In [4]:
random.shuffle(new_index)

In [7]:
df_exams['new_index']= new_index
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average,new_index
0,female,group B,bachelor's degree,standard,none,72,72,74,168.666667,242
1,female,group C,some college,standard,completed,69,90,88,188.333333,127
2,female,group B,master's degree,standard,none,90,95,93,216.000000,359
3,male,group A,associate's degree,free/reduced,none,47,57,44,118.666667,119
4,male,group C,some college,standard,none,76,78,75,179.000000,288
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,218.666667,850
996,male,group C,high school,free/reduced,none,62,55,55,135.333333,995
997,female,group C,high school,free/reduced,completed,59,71,65,151.666667,700
998,female,group D,some college,standard,completed,68,78,77,171.666667,723
999,female,group D,some college,free/reduced,none,77,86,86,191.666667,247

In [9]:
# set index
df_exams.set_index('new_index',inplace= True)

In [10]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
new_index,,,,,,,,,
242,female,group B,bachelor's degree,standard,none,72,72,74,168.666667
127,female,group C,some college,standard,completed,69,90,88,188.333333
359,female,group B,master's degree,standard,none,90,95,93,216.000000
119,male,group A,associate's degree,free/reduced,none,47,57,44,118.666667
288,male,group C,some college,standard,none,76,78,75,179.000000
...,...,...,...,...,...,...,...,...,...
850,female,group E,master's degree,standard,completed,88,99,95,218.666667
995,male,group C,high school,free/reduced,none,62,55,55,135.333333
700,female,group C,high school,free/reduced,completed,59,71,65,151.666667
723,female,group D,some college,standard,completed,68,78,77,171.666667
247,female,group D,some college,free/reduced,none,77,86,86,191.666667

In [13]:
df_exams.sort_index(inplace= True)

In [14]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
new_index,,,,,,,,,
0,male,group A,associate's degree,standard,none,67,57,53,141.666667
1,female,group C,associate's degree,standard,none,66,77,73,167.333333
2,male,group D,some high school,standard,completed,77,68,69,168.000000
3,male,group A,some college,standard,completed,61,51,52,129.333333
4,female,group C,bachelor's degree,standard,completed,92,100,99,225.000000
...,...,...,...,...,...,...,...,...,...
995,male,group C,high school,free/reduced,none,62,55,55,135.333333
996,female,group E,master's degree,standard,none,81,92,91,203.333333
997,male,group C,some high school,standard,none,73,66,66,161.000000
998,male,group D,some college,standard,none,67,64,70,154.333333
999,female,group B,some high school,standard,completed,32,51,44,97.666667

In [15]:
df_exams.sort_index(ascending=False,inplace= True)

In [16]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
new_index,,,,,,,,,
999,female,group B,some high school,standard,completed,32,51,44,97.666667
998,male,group D,some college,standard,none,67,64,70,154.333333
997,male,group C,some high school,standard,none,73,66,66,161.000000
996,female,group E,master's degree,standard,none,81,92,91,203.333333
995,male,group C,high school,free/reduced,none,62,55,55,135.333333
...,...,...,...,...,...,...,...,...,...
4,female,group C,bachelor's degree,standard,completed,92,100,99,225.000000
3,male,group A,some college,standard,completed,61,51,52,129.333333
2,male,group D,some high school,standard,completed,77,68,69,168.000000
1,female,group C,associate's degree,standard,none,66,77,73,167.333333
0,male,group A,associate's degree,standard,none,67,57,53,141.666667

# Rename Column

In [19]:
df_exams.rename(columns={'gender':'Gender'},inplace= True)

In [20]:
df_exams

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
new_index,,,,,,,,,
999,female,group B,some high school,standard,completed,32,51,44,97.666667
998,male,group D,some college,standard,none,67,64,70,154.333333
997,male,group C,some high school,standard,none,73,66,66,161.000000
996,female,group E,master's degree,standard,none,81,92,91,203.333333
995,male,group C,high school,free/reduced,none,62,55,55,135.333333
...,...,...,...,...,...,...,...,...,...
4,female,group C,bachelor's degree,standard,completed,92,100,99,225.000000
3,male,group A,some college,standard,completed,61,51,52,129.333333
2,male,group D,some high school,standard,completed,77,68,69,168.000000
1,female,group C,associate's degree,standard,none,66,77,73,167.333333
0,male,group A,associate's degree,standard,none,67,57,53,141.666667